using System;
using System.Collections.Generic;
using cryptlib;

namespace Pluralsight.TrustUs
{
/// <summary>
/// Class Program.
/// </summary>
/// <autogeneratedoc />
/// TODO Edit XML Comment Template for Program
    internal class Program
    {
        /// <summary>
        /// Defines the entry point of the application.
        /// </summary>
        /// <param name="args">The arguments.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Main
        private static void Main(string[] args)
        {
            crypt.Init();
            var trustUsCertificateAuthority = new CertificateAuthority();
            var rootCaConfiguration = new CertificateConfiguration
            {
                CertificateFileName = @"C:\Pluralsight\Keys\ca.cer",
                KeystoreFileName = @"C:\Pluralsight\Keys\ca.key",
                DistinguishedName = new DistinguishedName
                {
                    Country = "US",
                    State = "OH",
                    Locality = "Cleveland",
                    Organization = "Trust Us",
                    OrganizationalUnit = "Certificates",
                    CommonName = "Root Certificate"
                },
                KeyLabel = "Root",
                PrivateKeyPassword = "P@ssw0rd"
            };

            var intermediateCertificateAuthorities = new List<CertificateConfiguration>();
            intermediateCertificateAuthorities.Add(new CertificateConfiguration
            {
                CertificateFileName = @"C:\Pluralsight\Keys\clevelandIca.cer",
                KeystoreFileName = @"C:\Pluralsight\Keys\clevelandIca.key",
                DistinguishedName = new DistinguishedName
                {
                    Country = "US",
                    State = "OH",
                    Locality = "Cleveland",
                    Organization = "Trust Us",
                    OrganizationalUnit = "Certificates",
                    CommonName = "Cleveland Certificate"
                },
                KeyLabel = "Cleveland",
                PrivateKeyPassword = "P@ssw0rd",
                SigningKeyFileName = @"C:\Pluralsight\Keys\ca.key",
                SigningKeyLabel = "Root",
                SigningKeyPassword = "P@ssw0rd"
            });

            var done = false;
            do
            {
                switch (DisplayMenu())
                {
                    case 1:
                        trustUsCertificateAuthority.Install(rootCaConfiguration, intermediateCertificateAuthorities);
                        break;
                    case 5:
                        done = true;
                        break;
                }
            } while (!done);

            crypt.End();
        }

        /// <summary>
        /// Displays the menu.
        /// </summary>
        /// <returns>System.Int32.</returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for DisplayMenu
        public static int DisplayMenu()
        {
            Console.WriteLine("TrustUs Certificate Authority");
            Console.WriteLine();
            Console.WriteLine("1. Install Certificate Authority");
            Console.WriteLine("2. Create Key Pair");
            Console.WriteLine("3. ");
            Console.WriteLine("4. ");
            Console.WriteLine("5. Exit");
            var result = Console.ReadLine();
            return Convert.ToInt32(result);
        }
    }
}